# fly.toml app configuration file generated for data-intelligence-agent on 2025-10-05T18:12:53+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'data-intelligence-agent'
primary_region = 'sjc'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 1024
